### ISSUE TITLE
Refactor ci action to use a matrix of options

### ISSUE THREAD

**Issue by steve-downey** [beman-project/Optional26#33]
Right now the ci.yml specifies a collection of configs to run the matrix build over. It would be better style to set the variables and let CI construct the cartesian product:
```yaml
    strategy:
      matrix:
        clang-version: [17]
        os: [ubuntu-24.04]
        toolchain: [clang-17-toolchain.cmake, clang-18-toolchain.cmake, gcc-13-toolchain.cmake]
        
```        
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
